<?php include "header.phtml" ?>

    <?= $studentID = ""; $name = ""; $paper = ""; ?>
    <div class="container">
        <form action="../..//" method="post">
            <div class="form-group">
                <label class="col-sm-2">student ID:</label>
                <div class="notInline col-sm-4">
                    <input type="text" class="form-control" placeholder="Enter studentid" name="studentID" required="required">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2">Name:</label>
                <div class="notInline col-sm-4">
                    <input type="text" class="form-control" placeholder="Enter name" name="sName" required="required">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2">Paper:</label>
                <div class="notInline col-sm-4">
                    <input type="text" class="form-control" placeholder="Enter paper" name="sPaper" required="required">
                </div>
            </div>
            <div class="container-fluid">
                <li><a href=<?= $linkTo('Powerpoint'); ?>><span class="glyphicon glyphicon-user"></span>Attach Power Point</a></li>
            </div>
            <div><input type="checkbox" name="instruction" value="instructon" id="instruction"><label for="instruction"> I have read and agree above instructions</label></div>
            <div class="col-sm-4">
                <button name="Confirm" type="submit" class="btn btn-default">Confirm</button>
                <button name="Cancel" type="cancel" class="btn btn-default">Cancel</button>
            </div>
        </form>
    </div>

<?php include "footer.phtml" ?>